"""add user profiles and checklists

Revision ID: 8c5513c54f68
Revises: 9d309f7ea2e5
Create Date: 2026-06-26 15:40:36.104879
"""
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa
import geoalchemy2


revision: str = '8c5513c54f68'
down_revision: str | None = '9d309f7ea2e5'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('adoption_checklists',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('vet_info', sa.Boolean(), nullable=False),
    sa.Column('budget_ready', sa.Boolean(), nullable=False),
    sa.Column('space_ready', sa.Boolean(), nullable=False),
    sa.Column('family_agreed', sa.Boolean(), nullable=False),
    sa.Column('time_committed', sa.Boolean(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_adoption_checklists_user_id'), 'adoption_checklists', ['user_id'], unique=True)
    op.create_table('user_profiles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('housing_type', sa.String(length=40), nullable=True),
    sa.Column('household', sa.String(length=120), nullable=True),
    sa.Column('experience', sa.String(length=300), nullable=True),
    sa.Column('daily_hours', sa.String(length=40), nullable=True),
    sa.Column('intro', sa.String(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_profiles_user_id'), 'user_profiles', ['user_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_profiles_user_id'), table_name='user_profiles')
    op.drop_table('user_profiles')
    op.drop_index(op.f('ix_adoption_checklists_user_id'), table_name='adoption_checklists')
    op.drop_table('adoption_checklists')
    # ### end Alembic commands ###
