"""add adoptions and applications

Revision ID: cfb1b844dc28
Revises: f53ab3e2e308
Create Date: 2026-06-26 15:24:59.687652
"""
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa
import geoalchemy2


revision: str = 'cfb1b844dc28'
down_revision: str | None = 'f53ab3e2e308'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('adoption_applications',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('dog_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('submitted', 'reviewing', 'meeting', 'matched', 'closed', name='applicationstatus'), nullable=False),
    sa.Column('message', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['dog_id'], ['dogs.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_adoption_applications_dog_id'), 'adoption_applications', ['dog_id'], unique=False)
    op.create_index(op.f('ix_adoption_applications_user_id'), 'adoption_applications', ['user_id'], unique=False)
    op.create_table('adoptions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('dog_id', sa.Integer(), nullable=False),
    sa.Column('adopted_at', sa.Date(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['dog_id'], ['dogs.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_adoptions_dog_id'), 'adoptions', ['dog_id'], unique=False)
    op.create_index(op.f('ix_adoptions_user_id'), 'adoptions', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_adoptions_user_id'), table_name='adoptions')
    op.drop_index(op.f('ix_adoptions_dog_id'), table_name='adoptions')
    op.drop_table('adoptions')
    op.drop_index(op.f('ix_adoption_applications_user_id'), table_name='adoption_applications')
    op.drop_index(op.f('ix_adoption_applications_dog_id'), table_name='adoption_applications')
    op.drop_table('adoption_applications')
    sa.Enum(name='applicationstatus').drop(op.get_bind(), checkfirst=True)
    # ### end Alembic commands ###
