"""add journey entries

Revision ID: d25d20f62ea2
Revises: 8c5513c54f68
Create Date: 2026-06-27 09:25:25.594368
"""
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa
import geoalchemy2


revision: str = 'd25d20f62ea2'
down_revision: str | None = '8c5513c54f68'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('journey_entries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('dog_id', sa.Integer(), nullable=False),
    sa.Column('quarter_label', sa.String(length=20), nullable=True),
    sa.Column('title', sa.String(length=120), nullable=False),
    sa.Column('body', sa.String(), nullable=False),
    sa.Column('photo_url', sa.String(length=300), nullable=True),
    sa.Column('cheers', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['dog_id'], ['dogs.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_journey_entries_dog_id'), 'journey_entries', ['dog_id'], unique=False)
    op.create_index(op.f('ix_journey_entries_user_id'), 'journey_entries', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_journey_entries_user_id'), table_name='journey_entries')
    op.drop_index(op.f('ix_journey_entries_dog_id'), table_name='journey_entries')
    op.drop_table('journey_entries')
    # ### end Alembic commands ###
