"""initial

Revision ID: eb16956cfda8
Revises: 
Create Date: 2026-06-26 07:56:56.140722
"""
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa
import geoalchemy2
from geoalchemy2 import Geometry

revision: str = 'eb16956cfda8'
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('reports',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('target_type', sa.String(length=20), nullable=False),
    sa.Column('target_id', sa.Integer(), nullable=False),
    sa.Column('description', sa.String(), nullable=False),
    sa.Column('image_url', sa.String(length=300), nullable=True),
    sa.Column('reporter_contact', sa.String(length=120), nullable=True),
    sa.Column('ai_category', sa.String(length=60), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('admin_memo', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_geospatial_table('shelters',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('region', sa.String(length=40), nullable=False),
    sa.Column('address', sa.String(length=200), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('is_gov_registered', sa.Boolean(), nullable=False),
    sa.Column('gov_reg_no', sa.String(length=60), nullable=True),
    sa.Column('transparency_level', sa.Enum('unverified', 'basic', 'verified', name='transparencylevel'), nullable=False),
    sa.Column('source', sa.Enum('public_api', 'manual', name='datasource'), nullable=False),
    sa.Column('external_id', sa.String(length=80), nullable=True),
    sa.Column('phone', sa.String(length=40), nullable=True),
    sa.Column('lat', sa.Float(), nullable=True),
    sa.Column('lng', sa.Float(), nullable=True),
    sa.Column('location', Geometry(geometry_type='POINT', srid=4326, spatial_index=False, from_text='ST_GeomFromEWKT', name='geometry'), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_shelters_external_id'), 'shelters', ['external_id'], unique=False)
    op.create_index(op.f('ix_shelters_region'), 'shelters', ['region'], unique=False)
    op.create_table('dogs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('shelter_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.Column('breed_label', sa.String(length=80), nullable=True),
    sa.Column('breed_is_estimate', sa.Boolean(), nullable=False),
    sa.Column('age_estimate', sa.String(length=40), nullable=True),
    sa.Column('gender', sa.String(length=10), nullable=True),
    sa.Column('is_neutered', sa.Boolean(), nullable=True),
    sa.Column('adoption_status', sa.Enum('protected', 'available', 'reserved', 'adopted', name='adoptionstatus'), nullable=False),
    sa.Column('source', sa.Enum('public_api', 'manual', name='datasource'), nullable=False),
    sa.Column('external_id', sa.String(length=80), nullable=True),
    sa.Column('thumbnail_url', sa.String(length=300), nullable=True),
    sa.Column('story', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['shelter_id'], ['shelters.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_dogs_external_id'), 'dogs', ['external_id'], unique=False)
    op.create_table('passport_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('dog_id', sa.Integer(), nullable=False),
    sa.Column('event_type', sa.Enum('rescue', 'intake', 'medical', 'vaccination', 'neuter', 'available', 'adopted', 'post_adoption', name='passporteventtype'), nullable=False),
    sa.Column('event_date', sa.Date(), nullable=True),
    sa.Column('title', sa.String(length=120), nullable=False),
    sa.Column('memo', sa.String(), nullable=True),
    sa.Column('source', sa.Enum('public_api', 'manual', name='datasource'), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['dog_id'], ['dogs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('passport_events')
    op.drop_index(op.f('ix_dogs_external_id'), table_name='dogs')
    op.drop_table('dogs')
    op.drop_index(op.f('ix_shelters_region'), table_name='shelters')
    op.drop_index(op.f('ix_shelters_external_id'), table_name='shelters')
    op.drop_geospatial_table('shelters')
    op.drop_table('reports')
    # ### end Alembic commands ###
