"""add dog protect_end_date

Revision ID: f53ab3e2e308
Revises: 5f4e287304c9
Create Date: 2026-06-26 08:57:05.414686
"""
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa
import geoalchemy2


revision: str = 'f53ab3e2e308'
down_revision: str | None = '5f4e287304c9'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('dogs', sa.Column('protect_end_date', sa.Date(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('dogs', 'protect_end_date')
    # ### end Alembic commands ###
